export const Plataforms = [
  {
    id: 4,
    name: 'PC',
    slug: 'pc',
    games_count: 545944,
    image_background: 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 18227,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
    ],
  },
  {
    id: 187,
    name: 'PlayStation 5',
    slug: 'playstation5',
    games_count: 1224,
    image_background: 'https://media.rawg.io/media/games/5f6/5f61441e6338e9221f96a8f4c64c7bb8.jpg',
    image: null,
    year_start: 2020,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
      {
        id: 32,
        slug: 'destiny-2',
        name: 'Destiny 2',
        added: 14494,
      },
      {
        id: 3070,
        slug: 'fallout-4',
        name: 'Fallout 4',
        added: 14040,
      },
      {
        id: 41494,
        slug: 'cyberpunk-2077',
        name: 'Cyberpunk 2077',
        added: 13470,
      },
    ],
  },
  {
    id: 1,
    name: 'Xbox One',
    slug: 'xbox-one',
    games_count: 5690,
    image_background: 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
      {
        id: 28,
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        added: 16222,
      },
    ],
  },
  {
    id: 18,
    name: 'PlayStation 4',
    slug: 'playstation4',
    games_count: 6908,
    image_background: 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
      {
        id: 28,
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        added: 16222,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 15873,
      },
    ],
  },
  {
    id: 186,
    name: 'Xbox Series S/X',
    slug: 'xbox-series-x',
    games_count: 1064,
    image_background: 'https://media.rawg.io/media/games/840/8408ad3811289a6a5830cae60fb0b62a.jpg',
    image: null,
    year_start: 2020,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
      {
        id: 32,
        slug: 'destiny-2',
        name: 'Destiny 2',
        added: 14494,
      },
      {
        id: 41494,
        slug: 'cyberpunk-2077',
        name: 'Cyberpunk 2077',
        added: 13470,
      },
      {
        id: 766,
        slug: 'warframe',
        name: 'Warframe',
        added: 13057,
      },
    ],
  },
  {
    id: 7,
    name: 'Nintendo Switch',
    slug: 'nintendo-switch',
    games_count: 5599,
    image_background: 'https://media.rawg.io/media/games/8d6/8d69eb6c32ed6acfd75f82d532144993.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 15873,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 13923,
      },
      {
        id: 2454,
        slug: 'doom',
        name: 'DOOM (2016)',
        added: 13813,
      },
    ],
  },
  {
    id: 3,
    name: 'iOS',
    slug: 'ios',
    games_count: 77390,
    image_background: 'https://media.rawg.io/media/games/8d6/8d69eb6c32ed6acfd75f82d532144993.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3439,
        slug: 'life-is-strange-episode-1-2',
        name: 'Life is Strange',
        added: 15728,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 13923,
      },
      {
        id: 422,
        slug: 'terraria',
        name: 'Terraria',
        added: 13333,
      },
      {
        id: 766,
        slug: 'warframe',
        name: 'Warframe',
        added: 13057,
      },
      {
        id: 416,
        slug: 'grand-theft-auto-san-andreas',
        name: 'Grand Theft Auto: San Andreas',
        added: 11706,
      },
      {
        id: 23027,
        slug: 'the-walking-dead',
        name: 'The Walking Dead: Season 1',
        added: 11551,
      },
    ],
  },
  {
    id: 8,
    name: 'Nintendo 3DS',
    slug: 'nintendo-3ds',
    games_count: 1682,
    image_background:
      'https://media.rawg.io/media/screenshots/55f/55f3e8983c17a0ef9e6b18aedd4f6794.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 422,
        slug: 'terraria',
        name: 'Terraria',
        added: 13333,
      },
      {
        id: 22509,
        slug: 'minecraft',
        name: 'Minecraft',
        added: 8590,
      },
      {
        id: 2597,
        slug: 'lego-lord-of-the-rings',
        name: 'LEGO The Lord of the Rings',
        added: 5951,
      },
      {
        id: 250,
        slug: 'the-binding-of-isaac-rebirth',
        name: 'The Binding of Isaac: Rebirth',
        added: 5703,
      },
      {
        id: 3729,
        slug: 'lego-the-hobbit',
        name: 'LEGO The Hobbit',
        added: 5458,
      },
      {
        id: 4012,
        slug: 'resident-evil-revelations-biohazard-revelations',
        name: 'Resident Evil Revelations',
        added: 4423,
      },
    ],
  },
  {
    id: 9,
    name: 'Nintendo DS',
    slug: 'nintendo-ds',
    games_count: 2482,
    image_background:
      'https://media.rawg.io/media/screenshots/4f2/4f2246a85225b7a91d63990fe540b7c4.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 865,
        slug: 'call-of-duty-black-ops',
        name: 'Call of Duty: Black Ops',
        added: 6829,
      },
      {
        id: 3486,
        slug: 'syberia',
        name: 'Syberia',
        added: 6801,
      },
      {
        id: 2597,
        slug: 'lego-lord-of-the-rings',
        name: 'LEGO The Lord of the Rings',
        added: 5951,
      },
      {
        id: 5578,
        slug: 'grid',
        name: 'GRID (2008)',
        added: 5409,
      },
      {
        id: 4869,
        slug: 'tomb-raider-underworld',
        name: 'Tomb Raider: Underworld',
        added: 4917,
      },
      {
        id: 5528,
        slug: 'call-of-duty-world-at-war',
        name: 'Call of Duty: World at War',
        added: 4542,
      },
    ],
  },
  {
    id: 13,
    name: 'Nintendo DSi',
    slug: 'nintendo-dsi',
    games_count: 37,
    image_background:
      'https://media.rawg.io/media/screenshots/078/078629e997421ca28e9098bd7a87cb10.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 19309,
        slug: 'plants-vs-zombies-goty-edition',
        name: 'Plants vs. Zombies GOTY Edition',
        added: 3909,
      },
      {
        id: 949,
        slug: 'cut-the-rope',
        name: 'Cut the Rope',
        added: 669,
      },
      {
        id: 223378,
        slug: 'ace-attorney-investigations-miles-edgeworth',
        name: 'Ace Attorney Investigations - Miles Edgeworth',
        added: 202,
      },
      {
        id: 22727,
        slug: 'jagged-alliance',
        name: 'Jagged Alliance',
        added: 151,
      },
      {
        id: 53802,
        slug: 'dragons-lair',
        name: "Dragon's Lair",
        added: 77,
      },
      {
        id: 25953,
        slug: 'mario-vs-donkey-kong-minis-march-again',
        name: 'Mario vs. Donkey Kong: Minis March Again!',
        added: 36,
      },
    ],
  },
  {
    id: 5,
    name: 'macOS',
    slug: 'macos',
    games_count: 106004,
    image_background: 'https://media.rawg.io/media/games/8cc/8cce7c0e99dcc43d66c8efd42f9d03e3.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 21553,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
      {
        id: 12020,
        slug: 'left-4-dead-2',
        name: 'Left 4 Dead 2',
        added: 17337,
      },
      {
        id: 13537,
        slug: 'half-life-2',
        name: 'Half-Life 2',
        added: 15769,
      },
    ],
  },
  {
    id: 6,
    name: 'Linux',
    slug: 'linux',
    games_count: 78657,
    image_background: 'https://media.rawg.io/media/games/9fa/9fa63622543e5d4f6d99aa9d73b043de.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 18227,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
      {
        id: 12020,
        slug: 'left-4-dead-2',
        name: 'Left 4 Dead 2',
        added: 17337,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 15873,
      },
      {
        id: 13537,
        slug: 'half-life-2',
        name: 'Half-Life 2',
        added: 15769,
      },
    ],
  },
  {
    id: 14,
    name: 'Xbox 360',
    slug: 'xbox360',
    games_count: 2805,
    image_background: 'https://media.rawg.io/media/games/4a0/4a0a1316102366260e6f38fd2a9cfdce.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 18227,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
      {
        id: 12020,
        slug: 'left-4-dead-2',
        name: 'Left 4 Dead 2',
        added: 17337,
      },
    ],
  },
  {
    id: 80,
    name: 'Xbox',
    slug: 'xbox-old',
    games_count: 741,
    image_background: 'https://media.rawg.io/media/games/74c/74ca0ec569682a150f3c6f9f661fb6a5.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 13537,
        slug: 'half-life-2',
        name: 'Half-Life 2',
        added: 15769,
      },
      {
        id: 416,
        slug: 'grand-theft-auto-san-andreas',
        name: 'Grand Theft Auto: San Andreas',
        added: 11706,
      },
      {
        id: 430,
        slug: 'grand-theft-auto-vice-city',
        name: 'Grand Theft Auto: Vice City',
        added: 9613,
      },
      {
        id: 19301,
        slug: 'counter-strike',
        name: 'Counter-Strike',
        added: 9218,
      },
      {
        id: 2361,
        slug: 'psychonauts',
        name: 'Psychonauts',
        added: 8271,
      },
      {
        id: 432,
        slug: 'grand-theft-auto-iii',
        name: 'Grand Theft Auto III',
        added: 7196,
      },
    ],
  },
  {
    id: 16,
    name: 'PlayStation 3',
    slug: 'playstation3',
    games_count: 3167,
    image_background: 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 21911,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 20466,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 18227,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 17538,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 17439,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 16464,
      },
    ],
  },
  {
    id: 15,
    name: 'PlayStation 2',
    slug: 'playstation2',
    games_count: 2058,
    image_background: 'https://media.rawg.io/media/games/fee/fee0100afd87b52bfbd33e26689fa26c.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 416,
        slug: 'grand-theft-auto-san-andreas',
        name: 'Grand Theft Auto: San Andreas',
        added: 11706,
      },
      {
        id: 18080,
        slug: 'half-life',
        name: 'Half-Life',
        added: 11342,
      },
      {
        id: 430,
        slug: 'grand-theft-auto-vice-city',
        name: 'Grand Theft Auto: Vice City',
        added: 9613,
      },
      {
        id: 2361,
        slug: 'psychonauts',
        name: 'Psychonauts',
        added: 8271,
      },
      {
        id: 432,
        slug: 'grand-theft-auto-iii',
        name: 'Grand Theft Auto III',
        added: 7196,
      },
      {
        id: 56184,
        slug: 'resident-evil-4',
        name: 'Resident Evil 4 (2005)',
        added: 6894,
      },
    ],
  },
  {
    id: 27,
    name: 'PlayStation',
    slug: 'playstation1',
    games_count: 1679,
    image_background: 'https://media.rawg.io/media/games/96a/96a48ac7487d9db9179d83170afcb16a.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 5159,
        slug: 'resident-evil-2',
        name: 'Resident Evil 2 (1998)',
        added: 6368,
      },
      {
        id: 5193,
        slug: 'oddworld-abes-oddysee',
        name: "Oddworld: Abe's Oddysee",
        added: 5743,
      },
      {
        id: 3449,
        slug: 'resident-evil',
        name: 'Resident Evil',
        added: 5412,
      },
      {
        id: 52939,
        slug: 'final-fantasy-vii',
        name: 'Final Fantasy VII (1997)',
        added: 4296,
      },
      {
        id: 20569,
        slug: 'ufo-enemy-unknown',
        name: 'X-COM: UFO Defense',
        added: 3648,
      },
      {
        id: 57908,
        slug: 'tomb-raider-ii',
        name: 'Tomb Raider II',
        added: 3255,
      },
    ],
  },
  {
    id: 19,
    name: 'PS Vita',
    slug: 'ps-vita',
    games_count: 1450,
    image_background: 'https://media.rawg.io/media/games/471/4712c9ac591f556f553556b864a7e92b.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 802,
        slug: 'borderlands-2',
        name: 'Borderlands 2',
        added: 15755,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 13923,
      },
      {
        id: 422,
        slug: 'terraria',
        name: 'Terraria',
        added: 13333,
      },
      {
        id: 23027,
        slug: 'the-walking-dead',
        name: 'The Walking Dead: Season 1',
        added: 11551,
      },
      {
        id: 3612,
        slug: 'hotline-miami',
        name: 'Hotline Miami',
        added: 10778,
      },
      {
        id: 654,
        slug: 'stardew-valley',
        name: 'Stardew Valley',
        added: 10754,
      },
    ],
  },
  {
    id: 17,
    name: 'PSP',
    slug: 'psp',
    games_count: 1374,
    image_background: 'https://media.rawg.io/media/games/9ca/9ca31615beee447f3ae1dc9b3b736dce.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 13886,
        slug: 'star-wars-battlefront-ii-2',
        name: 'Star Wars: Battlefront II (2005)',
        added: 4849,
      },
      {
        id: 5298,
        slug: 'tomb-raider-legend',
        name: 'Tomb Raider: Legend',
        added: 4477,
      },
      {
        id: 5297,
        slug: 'tomb-raider-anniversary',
        name: 'Tomb Raider: Anniversary',
        added: 4371,
      },
      {
        id: 16543,
        slug: 'lego-batman',
        name: 'LEGO Batman',
        added: 3202,
      },
      {
        id: 58890,
        slug: 'need-for-speed-most-wanted',
        name: 'Need For Speed: Most Wanted',
        added: 3062,
      },
      {
        id: 13926,
        slug: 'prince-of-persia-the-two-thrones',
        name: 'Prince of Persia: The Two Thrones',
        added: 2836,
      },
    ],
  },
  {
    id: 10,
    name: 'Wii U',
    slug: 'wii-u',
    games_count: 1114,
    image_background: 'https://media.rawg.io/media/games/6c8/6c8cb4780ce30b76b944cf656e8fff49.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 422,
        slug: 'terraria',
        name: 'Terraria',
        added: 13333,
      },
      {
        id: 3144,
        slug: 'super-meat-boy',
        name: 'Super Meat Boy',
        added: 9636,
      },
      {
        id: 3841,
        slug: 'assassins-creed-iv-black-flag',
        name: 'Assassin’s Creed IV: Black Flag',
        added: 9526,
      },
      {
        id: 22509,
        slug: 'minecraft',
        name: 'Minecraft',
        added: 8590,
      },
      {
        id: 3687,
        slug: 'watch-dogs',
        name: 'Watch Dogs',
        added: 8240,
      },
      {
        id: 3876,
        slug: 'deus-ex-human-revolution-directors-cut',
        name: "Deus Ex: Human Revolution - Director's Cut",
        added: 7707,
      },
    ],
  },
  {
    id: 11,
    name: 'Wii',
    slug: 'wii',
    games_count: 2209,
    image_background: 'https://media.rawg.io/media/games/9ca/9ca31615beee447f3ae1dc9b3b736dce.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 56184,
        slug: 'resident-evil-4',
        name: 'Resident Evil 4 (2005)',
        added: 6894,
      },
      {
        id: 865,
        slug: 'call-of-duty-black-ops',
        name: 'Call of Duty: Black Ops',
        added: 6829,
      },
      {
        id: 11276,
        slug: 'call-of-duty-modern-warfare-3',
        name: 'Call of Duty: Modern Warfare 3',
        added: 6237,
      },
      {
        id: 2597,
        slug: 'lego-lord-of-the-rings',
        name: 'LEGO The Lord of the Rings',
        added: 5951,
      },
      {
        id: 4869,
        slug: 'tomb-raider-underworld',
        name: 'Tomb Raider: Underworld',
        added: 4917,
      },
      {
        id: 1140,
        slug: 'world-of-goo',
        name: 'World of Goo',
        added: 4557,
      },
    ],
  },
  {
    id: 105,
    name: 'GameCube',
    slug: 'gamecube',
    games_count: 634,
    image_background: 'https://media.rawg.io/media/games/45f/45f6d31b0fcefe029e33d258a7beb6a2.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 56184,
        slug: 'resident-evil-4',
        name: 'Resident Evil 4 (2005)',
        added: 6894,
      },
      {
        id: 5159,
        slug: 'resident-evil-2',
        name: 'Resident Evil 2 (1998)',
        added: 6368,
      },
      {
        id: 19592,
        slug: 'hitman-2-silent-assassin',
        name: 'Hitman 2: Silent Assassin',
        added: 4622,
      },
      {
        id: 5298,
        slug: 'tomb-raider-legend',
        name: 'Tomb Raider: Legend',
        added: 4477,
      },
      {
        id: 12018,
        slug: 'star-wars-jedi-knight-ii-jedi-outcast',
        name: 'Star Wars Jedi Knight II: Jedi Outcast',
        added: 3793,
      },
      {
        id: 13909,
        slug: 'prince-of-persia-the-sands-of-time',
        name: 'Prince of Persia: The Sands of Time',
        added: 3425,
      },
    ],
  },
  {
    id: 83,
    name: 'Nintendo 64',
    slug: 'nintendo-64',
    games_count: 363,
    image_background:
      'https://media.rawg.io/media/screenshots/c1f/c1fd8b15793743563367688b3dd5faa6.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 5159,
        slug: 'resident-evil-2',
        name: 'Resident Evil 2 (1998)',
        added: 6368,
      },
      {
        id: 54491,
        slug: 'quake',
        name: 'Quake',
        added: 3275,
      },
      {
        id: 20466,
        slug: 'worms-armageddon',
        name: 'Worms Armageddon',
        added: 3131,
      },
      {
        id: 54492,
        slug: 'quake-2',
        name: 'Quake II',
        added: 2766,
      },
      {
        id: 25097,
        slug: 'the-legend-of-zelda-ocarina-of-time',
        name: 'The Legend of Zelda: Ocarina of Time',
        added: 1788,
      },
      {
        id: 28532,
        slug: 'banjo-kazooie',
        name: 'Banjo-Kazooie',
        added: 1554,
      },
    ],
  },
  {
    id: 24,
    name: 'Game Boy Advance',
    slug: 'game-boy-advance',
    games_count: 950,
    image_background: 'https://media.rawg.io/media/games/98c/98c87b286cd2a2ba942167df384a9bd3.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 53341,
        slug: 'jet-set-radio-2012',
        name: 'Jet Set Radio',
        added: 5293,
      },
      {
        id: 17975,
        slug: 'doom-ii',
        name: 'DOOM II',
        added: 3326,
      },
      {
        id: 19646,
        slug: 'splinter-cell',
        name: "Tom Clancy's Splinter Cell",
        added: 2247,
      },
      {
        id: 53446,
        slug: 'need-for-speed-underground-2-2',
        name: 'Need for Speed: Underground 2',
        added: 2186,
      },
      {
        id: 4005,
        slug: 'wolfenstein-3d',
        name: 'Wolfenstein 3D',
        added: 1914,
      },
      {
        id: 5265,
        slug: 'need-for-speed-carbon',
        name: 'Need For Speed Carbon',
        added: 1694,
      },
    ],
  },
  {
    id: 43,
    name: 'Game Boy Color',
    slug: 'game-boy-color',
    games_count: 426,
    image_background: 'https://media.rawg.io/media/games/28b/28b088364ecab7870dffc3b710104734.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 20466,
        slug: 'worms-armageddon',
        name: 'Worms Armageddon',
        added: 3131,
      },
      {
        id: 57607,
        slug: 'metal-gear-solid-1',
        name: 'Metal Gear Solid',
        added: 2214,
      },
      {
        id: 52997,
        slug: 'grand-theft-auto-2-1999',
        name: 'Grand Theft Auto 2',
        added: 1984,
      },
      {
        id: 52998,
        slug: 'grand-theft-auto-1998',
        name: 'Grand Theft Auto',
        added: 1910,
      },
      {
        id: 25080,
        slug: 'super-mario-bros',
        name: 'Super Mario Bros.',
        added: 1479,
      },
      {
        id: 24030,
        slug: 'super-mario-bros-3',
        name: 'Super Mario Bros. 3',
        added: 1163,
      },
    ],
  },
  {
    id: 26,
    name: 'Game Boy',
    slug: 'game-boy',
    games_count: 617,
    image_background: 'https://media.rawg.io/media/games/057/0573c1c9e1f2414c1f4acabe86ee9fd9.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 5383,
        slug: 'worms',
        name: 'Worms',
        added: 2114,
      },
      {
        id: 52998,
        slug: 'grand-theft-auto-1998',
        name: 'Grand Theft Auto',
        added: 1910,
      },
      {
        id: 52175,
        slug: 'battletoads',
        name: 'Battletoads',
        added: 1856,
      },
      {
        id: 54285,
        slug: 'mortal-kombat',
        name: 'Mortal Kombat',
        added: 1767,
      },
      {
        id: 14829,
        slug: 'turok',
        name: 'Turok: Dinosaur Hunter',
        added: 1418,
      },
      {
        id: 23762,
        slug: 'pokemon-red',
        name: 'Pokémon Red, Blue, Yellow',
        added: 1062,
      },
    ],
  },
  {
    id: 79,
    name: 'SNES',
    slug: 'snes',
    games_count: 982,
    image_background: 'https://media.rawg.io/media/games/087/08727beb32c364d30e8b2a1aa8595f8e.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 5383,
        slug: 'worms',
        name: 'Worms',
        added: 2114,
      },
      {
        id: 4005,
        slug: 'wolfenstein-3d',
        name: 'Wolfenstein 3D',
        added: 1914,
      },
      {
        id: 54285,
        slug: 'mortal-kombat',
        name: 'Mortal Kombat',
        added: 1767,
      },
      {
        id: 52884,
        slug: 'doom-2',
        name: 'DOOM',
        added: 1628,
      },
      {
        id: 1063,
        slug: 'final-fantasy-vi',
        name: 'FINAL FANTASY VI',
        added: 1539,
      },
      {
        id: 24899,
        slug: 'super-mario-world',
        name: 'Super Mario World',
        added: 1502,
      },
    ],
  },
  {
    id: 49,
    name: 'NES',
    slug: 'nes',
    games_count: 1015,
    image_background: 'https://media.rawg.io/media/games/7c5/7c50dd0415eb0a57505c58d4e50e4d24.jpg',
    image: null,
    year_start: null,
    year_end: null,
    games: [
      {
        id: 54122,
        slug: 'ultima-4-quest-of-the-avatar',
        name: 'Ultima IV: Quest of the Avatar',
        added: 2272,
      },
      {
        id: 52175,
        slug: 'battletoads',
        name: 'Battletoads',
        added: 1856,
      },
      {
        id: 25080,
        slug: 'super-mario-bros',
        name: 'Super Mario Bros.',
        added: 1479,
      },
      {
        id: 24030,
        slug: 'super-mario-bros-3',
        name: 'Super Mario Bros. 3',
        added: 1163,
      },
      {
        id: 24881,
        slug: 'pac-man',
        name: 'Pac-Man',
        added: 817,
      },
      {
        id: 53239,
        slug: 'disneys-aladdin-1993',
        name: "Disney's Aladdin",
        added: 748,
      },
    ],
  },
]
